### ISSUE TITLE
Add install "How to" on README

### ISSUE THREAD

**Issue by gavinfay** [shcaba/SS-DL-tool#12]
Suggestion to add a brief installation 'how to' guide to the README or wiki to guide users on getting set up to use the package.

Use is pretty intuitive once someone has it runnning, but some friendly help on the repo to get started would really help I think.

Perhaps something along the lines of the [RStudio shiny example here.](https://github.com/rstudio/shiny_example)

**Comment by shcaba** [comment]
Thank you for this suggestion!
Just added stuff to the development branch, so an update will be coming soon!
