### ISSUE TITLE
update install instructions to account for package not on CRAN

### ISSUE THREAD

**Issue by iantaylor-NOAA** [shcaba/SS-DL-tool#19]
The README includes this line: `install.packages(c("devtools","shiny","shinyjs","r4ss","ggplot2","reshape2","dplyr","tidyr","rlist","viridis","sss","shinyWidgets","shinyFiles","HandyCode","plyr","shinybusy"))`
This installs a bunch of packages that are on CRAN. However, the `r4ss` on CRAN is old and won't work for recent SS models, and `HandyCode` isn't on CRAN at all. The latter issue causes this warning
```
Warning messages:
1: package 'HandyCode' is not available
```
I would remove both packages from that line and add `remotes::install_github("chantelwetzel-noaa/HandyCode")`
further down, after the other, similar `install_github()` commands.

Thanks to @k-doering-NOAA for noting that students in an ongoing course had issues with this.

**Comment by iantaylor-NOAA** [comment]
Also, @chantelwetzel-noaa might have ideas about `HandyCode`, which is also discussed on this issue https://github.com/nwfsc-assess/nwfscDiag/issues/1

**Comment by shcaba** [comment]
Thanks for catching these!
Changes have been made.
