### ISSUE TITLE
Which of your papers can I refer to for further understanding of these three model differences?

### ISSUE THREAD

**Issue by Hanqingpeng** [shcaba/SS-DL-tool#39]
"Length-only models. These are akin to LBSPR (Hordyk et al. 2015) and LIME (Rudd and Thorson 2017). Both styles of length-only models can be performed in this tool (determined by the estimation of recruitment)"
Does this mean that this is equivalent to LBSPR (Hordyk et al. 2015) or LIME (Rudd and Thorson 2017)? Or can it achieve the same effect?
Which of your papers can I refer to for further understanding of these three model differences?

**Comment by shcaba** [comment]
The paper regarding simulation testing of this mode is in progress.
The intent of this approach, though, is to provide a more flexible approach than LBSPR (e.g., allow for multiple fleets and more variable selectivity forms) while integrating multiple years of data like LIME does. While it is not a random effects model like LIME, it is an integrated model like LIME.
