### ISSUE TITLE
Shiny App crashes when navigating to different tabs

### ISSUE THREAD

**Issue by thalassa0** [shcaba/SS-DL-tool#53]
The model was run using  an existing model file
The run went smoothly, the plots appeared in their own window, the app appeared in its own separate window ,  however when navigating to a different tab, the app disappeared

Strangely, in the scenarios folder, the scenario name was embedded repeatedly (multiple times) and the file/directory name was too long. That may have caused the problem.

**Comment by shcaba** [comment]
I have removed the choose your own folder option, as it is rarely used and causes this issue.
I will close this issue for now and revisit it later if I go back to considering offering folder saving options.
