### ISSUE TITLE
Record state of SS-DL prior to run via bookmarking

### ISSUE THREAD

**Issue by BMC1986** [shcaba/SS-DL-tool#61]
This is a suggestion for how to handle unknown errors and save time in rerunning the SS-DL tool

Save the state of the Shiny session prior to pressing "Run Model" button via bookmarking or have a separate bookmark button.
Recall that bookmarked state if model run fails and tools is reloaded.

https://shiny.posit.co/r/reference/shiny/1.6.0/enablebookmarking
https://shiny.posit.co/r/articles/share/bookmarking-state/

**Comment by shcaba** [comment]
Booking marking completed.
