### ISSUE TITLE
length dimension

### ISSUE THREAD

**Issue by Efesosa** [shcaba/SS-DL-tool#77]
To allow for flexible length dimension and ranges. It is troublesome when one is working with spiny lobsters measuring 120 mm to 270 mm (bin width= 5 mm), even though we convert to cm. The latter since the range 12 to 27 is too narrow.

**Comment by shcaba** [comment]
You should be able to set the bin widths (in cm) to whatever you would like. For you example, you could use a bin width of 0.5 cm.  Does that work for you?

**Comment by Efesosa** [comment]
Hi,I have tested that option and did not work. When I gave click to run the model just a gray shadow appears on the screen instead of the regular sign of "model running"
My data set is quite simple, one fleet, combined sex (= 0), 10 fishing seasons of size structure and life history parameters. After the Length Only approach I am planning to use the catch and length option.
Regards,Eloy Sosa C. 
    El lunes, 13 de mayo de 2024, 16:54:27 GMT-5, Jason Cope ***@***.***> escribió:  
 
 


You should be able to set the bin widths (in cm) to whatever you would like. For you example, you could use a bin width of 0.5 cm. Does that work for you?

**Comment by shcaba** [comment]
Would it be possible for you to share you files with me? If you are using the latest version of the tool, I would just need your input.RDS and data file found in the Scenario_Inputs folder. 
If using an older version, I would need the data file and life history inputs.
This would help me see the error clearer and provide a solution.
Thanks for reaching out.

**Comment by Efesosa** [comment]
Dear Dr. Cope:
I am sending two files containing data on 1) spiny lobster length, cm of tail length, the midpoint of bins (0.5 cm bin width), for 10 fishing seasons 2010- 2022. Combined sexes, only one fleet; 2) landings data, tons of tails (weight) for fishing seasons 2001- 2022.

Life history parameter values are:
M= 0.35 (1/year); Linf= 27.6 cm tail length, k= 0.24 (1/year), t0= 0.44 years; Maturity, Lm50= 14 cm, Lm95= 17.5 cm; Selectivity, SL50= 14.5 cm, SL= 17.5 cm (Initial values).
W-L a= 0.00005038     W-L b= 3.065           W (Kg of tail), L (cm of tail). 

I have tested several alternatives... using mm of length, merging bins, change to cm of length without success.Thanks in advance,
Eloy Sosa CorderoECOSUR-Unidad ChetumalMexican Caribbean

    El miércoles, 15 de mayo de 2024, 10:56:23 GMT-5, Jason Cope ***@***.***> escribió:  
 
 


Would it be possible for you to share you files with me? If you are using the latest version of the tool, I would just need your input.RDS and data file found in the Scenario_Inputs folder.
If using an older version, I would need the data file and life history inputs.
This would help me see the error clearer and provide a solution.
Thanks for reaching out.

**Comment by shcaba** [comment]
We can confirm that using <1cm bins in SS3 is not an issue. Eloy and I are working on specifics of his assessment via email, so I will close this issue here.
