### ISSUE TITLE
Citation file in Github

### ISSUE THREAD

**Issue by descambrleR** [shcaba/SS-DL-tool#80]
Please could you add a citation file in the repository? https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

Cheers

**Comment by shcaba** [comment]
Thank you for your suggestion. I have now added a .ciff file for citation purposes. I also suggest considering citing the first paper that mentions this tool: 
Cope, J.M., 2024. The good practices of practicable alchemy in the stock assessment continuum: Fundamentals and principles of analytical methods to support science-based fisheries management under data and resource limitations. Fisheries Research 270, 106859. https://doi.org/10.1016/j.fishres.2023.106859
